return {

	_Properties = {
		AutoButtonColor = false,
		BackgroundColor3 = Color3.new(0, 0, 0),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
	},

	_Attributes = {
		["TI.Time"] = 0.5,

		Text = "",
		Image = "",

		TextColor = Color3.new(1, 1, 1),
		TextShadowColor = Color3.new(0.5, 0.5, 0.5),
		--Color1 = Color3.fromRGB(0, 57, 100),
		--Color2 = Color3.fromRGB(0, 144, 255),

		UICornerRadius = UDim.new(0, 0),
		UIPadding = UDim.new(0, 0),
	},
}
